### ISSUE TITLE
RSelenium: Switch to docker

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19CanadaData#11]
RSelenium has 3 primary ways of running the Selenium Server / headless browser / webdriver combo:

* Manually
* Using `docker`
* Using `wdman`

The main options for browser are Chrome/Chromium and Firefox.

Presently, the package uses `wdman` with Firefox. However, this has [issues](https://github.com/ropensci/wdman/issues/27) on Linux and Firefox is much less commonly installed than Chrome/Chromium. The [chromedriver](https://github.com/ccodwg/Covid19CanadaData/tree/chromedriver) branch switches this over to Chrome/Chromium. However, this presents its own issues, particularly because the latest Chromedriver version may be ahead of the latest stable version of Chrome/Chromium, meaning the user must specify the version of Chromedriver to use.

Docker removes the fiddliness (although most users will not have docker installed). Still, it seems like the best way of achieving reproducible, pain-free RSelenium environments.

Docker may be controlled from R using the [`stevedore`](https://github.com/richfitz/stevedore) package. However, Windows support is limited and requires the `reticulate` package (provides a wrapper around the Python API). This would require extra documentation.

Include documentation for installing:

* https://docs.ropensci.org/RSelenium/articles/docker.html
* Run docker without sudo on Linux: https://docs.docker.com/engine/install/linux-postinstall/
* Simple install of docker rootless mode: https://itnext.io/docker-running-in-rootless-mode-bdbcfc728b3a
* Must support `host` argument of `docker_available()` and `docker_client()` (e.g., host = "unix:///run/user/1000/docker.sock" for a Linux docker rootless install)

**Comment by jeanpaulrsoucy** [comment]
Note that the [selenium/standalone-chrome](https://hub.docker.com/r/selenium/standalone-chrome) image used in `webdriver` is for the `x86_64` architecture. For the `arm64` architecture (e.g., M1 Mac), there is the new [seleniarm/standalone-chromium](https://hub.docker.com/r/seleniarm/standalone-chromium) image (see: https://github.com/SeleniumHQ/docker-selenium/issues/1076#issuecomment-788343926).

Which image to use could be distinguished by the result of `Sys.info()["machine"]`.

**Comment by jeanpaulrsoucy** [comment]
Function should check if the relevant Docker image is available and if not, ask permission to download (rather than doing it automatically).

**Comment by jamesmortensen** [comment]
@jeanpaulrsoucy I've been building ARM64 versions of some of the Docker Selenium images for some time now.  I just pushed some updated versions of the ARM64 Docker Selenium images to Docker Hub.  They can be found here:  https://hub.docker.com/u/seleniarm.  

This also includes the noVNC client/server listening on port 7900.

**Comment by jeanpaulrsoucy** [comment]
@jamesmortensen Thanks for your work on this! I can confirm it works on Apple silicon and fixes the issue I was having with cross-platform compatibility. Nice to see the "latest" tag on the new version, as well!

**Comment by jeanpaulrsoucy** [comment]
Potentially add a debug mode for VNC viewer:

https://dev.to/automationbro/debug-selenium-tests-in-docker-using-vnc-viewer-59nj

**Comment by jamesmortensen** [comment]
@jeanpaulrsoucy The new seleniarm/standalone-chromium images have the VNC, and noVNC, by default.  SeleniumHQ no longer splits into debug and non-debug images.  Hope this helps.
